---
default_stages:
  - pre-commit
fail_fast: false
minimum_pre_commit_version: 2.15.0

repos:
  # Common hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      # Git hooks
      - id: check-added-large-files
        args:
          - --maxkb=2000
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-submodules
      - id: no-commit-to-branch
        args:
          - --branch
          - main

      # Common errors
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md,markdown,mdown,mkd"

      # JSON
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-ensure-ascii

      # Cross platform
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: destroyed-symlinks
      - id: mixed-line-ending
        args:
          - --fix=lf

      # Security
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

      # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args:
          - --django
      - id: requirements-txt-fixer

  # Dockerfile hook
  - repo: https://github.com/hadolint/hadolint
    rev: 33deb7817c88475caa1ce7d832922ff0f674fa15 # v2.13.1
    hooks:
      - id: hadolint

  # Helm hook
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 40f924cd642f5dc98d12bd97b07f3752223553da # v0.1.30
    hooks:
      - id: helmlint

  # Terraform and Terragrunt hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 9a790d2bbf52124eecb5a71a4bab4884804ffa2a # v1.100.0
    hooks:
      - id: terragrunt_fmt
      # - id: terragrunt_validate
      #   exclude: "^terragrunt.hcl$"
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-diff
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=SPECS.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint

  - repo: local
    hooks:
      - id: tfsort
        name: tfsort
        entry: hooks/tfsort.sh
        language: script
        types:
          - terraform

  # Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: 4fb43823ef3d152d239e92d7d5cb04783b548062 # v8.28.0
    hooks:
      - id: gitleaks

  # YAML
  - repo: https://github.com/google/yamlfmt
    rev: 398e72ad8473251b65d9da2cbd43a4b92a61fab7 # v0.17.2
    hooks:
      - id: yamlfmt

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=.yamllint.yml

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=100"
          - "--ignore=E203,E266,E501,W503"

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--filter-files"
