---
- id: tfsort
  name: tfsort
  description: Run tfsort on all Terraform files
  entry: hooks/tfsort.sh
  language: script
  files: ^.*\/.*\.(tf|tofu|hcl)$
  exclude: \.terraform\/.*$
  types:
    - terraform
